---
title: "Date exploratory - Group Project"
output: html_document
date: "2025-03-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r pressure, echo=FALSE}
library(zoo)
library(lubridate)
library(mgcv)
library(TSA)
library(dynlm)
library(tseries)
library(car)
library(MuMIn)
library(ggplot2)
library(reshape2)
library(greybox)
library(mlr)
library(dplyr)
library(data.table)
library(urca)
library(devtools)
library(prophet)
library(rugarch)
```

First I load and plot the data, with respective ACF plot.
```{r}
saving_df <- read.csv("Personal Saving Rate.csv")
saving <- ts(saving_df$PSAVER, start = c(1987, 1), frequency = 12) 
ts.plot(saving, ylab="Personal Saving Rate")
acf(saving, lag.max = 12*30)
```
I aggregate the data the monthly data into quarterly data.

```{r}
saving_q <- aggregate(saving, nfrequency = 4)
ts.plot(saving_q, ylab="Personal Saving Rate")
acf(saving_q, lag.max = 12*30)
```
Outliers 2020...

I calulculate spline trend.
```{r}
time.pts = c(1:length(saving_q))
time.pts = c(time.pts - min(time.pts))/max(time.pts)

spl = gam(saving_q~s(time.pts)) #Spline
spl_ts = ts(fitted(spl),start=1987,frequency=4)

ts.plot(saving_q,ylab="Personal Saving Rate",main="Personal Saving Rate with Trend Estimations")
lines(spl_ts,lwd=2,col="red")
```

```{r}
res_spl <- saving_q - spl_ts

plot(res_spl, type = "l",main="Residuals Spline detrended")
acf(res_spl, lag.max = 4*30, main='Spline detrended Residuals')
```
There might be some heteroskedasticity...

I clalculate the trend+seasonality.
```{r}
time.pts2 = c(1:length(saving_q))
time.pts2 = c(time.pts2 - min(time.pts2))/max(time.pts2)

gam_ses = gam(saving_q~s(time.pts2)+season(saving_q))
gam_ses_ts = ts(fitted(gam_ses),start=1987,frequency=4)

plot(saving_q, type = "l",ylab="Personal Saving Rate",main="Personal Saving Rate trend+seasonality Estimations")
lines(gam_ses_ts, lwd=2, col="red")
```
```{r}
res_2 <- saving_q - gam_ses_ts

plot(res_2, type = "l",main="Residuals Trend+Seasonality")
acf(res_2, lag.max = 4*50, main='Trend+Seasonality Residuals')
```
Still might be some heterosckedasticity.

I differenciate the data.
```{r}
diff_ts = diff(ts(saving_q,start=1987,frequency=4))

plot(diff_ts, type = "l",main="Residuals Differencing")
acf(diff_ts, lag.max = 4*30, main='Differencing Residuals')
```
Start using ARIMA.
```{r}
n <- length(res_2)
p <- 0:6
q <- 0:6
aic <- matrix(0, length(p), length(q)) 
for (i in 1:length(p)) {
  for (j in 1:length(q)) {
    modij = arima(res_2, order = c(p[i], 0, q[j]), method = 'ML')
    aic[i, j] = modij$aic + 2 * (p[i] + q[j] + 1) * (p[i] + q[i]) / (n - p[i] - q[j] - 1)
  }
}


norder = 7
aicv = as.vector(aic)
plot(aicv, ylab = "AIC values")
indexp = rep(c(1:norder),norder)
indexq = rep(c(1:norder),each=norder)
indexaic = which(aicv == min(aicv))
porder = indexp[indexaic]-1
qorder = indexq[indexaic]-1
cat("The p order is ", porder)
cat("\nThe q order is ", qorder)
```
```{r}
res_model = arima(res_2, order = c(2, 0, 5), method = 'ML')
res_model
```
```{r}
ts.plot(residuals(res_model),ylab = "Residual Process")
acf(residuals(res_model),lag.max = 4*30)
pacf(residuals(res_model),lag.max = 4*30)
qqPlot(residuals(res_model), ylab = "Residuals")
Box.test(res_model$resid, lag = (2 + 5 + 1), type = "Ljung-Box", fitdf = (2+5))
```






```{r}

test_modelA <- function(p,d,q){
  mod = arima(saving_q, order=c(p,d,q), method="ML", include.mean = TRUE)
  current.aic = AIC(mod)
  df = data.frame(p,d,q,current.aic)
  names(df) <- c("p","d","q","AIC")
  #print(paste(p,d,q,current.aic,sep=" "))
  return(df)
}

orders = data.frame(Inf,Inf,Inf,Inf)
names(orders) <- c("p","d","q","AIC")


for (p in 0:8){
  for (d in 0:1){
    for (q in 0:8) {
      possibleError <- tryCatch(
        orders<-rbind(orders,test_modelA(p,d,q)),
        error=function(e) e
      )
      if(inherits(possibleError, "error")) next
      
    }
  }
}
orders <- orders[order(orders$AIC),]
orders

```
```{r}
model <- arima(saving_q, order = c(1,1,4), method = "ML", include.mean = TRUE)
model
```

```{r}
ts.plot(residuals(model),ylab = "Residual Process")
acf(residuals(model),lag.max = 4*30)
pacf(residuals(model),lag.max = 4*30)
qqPlot(residuals(model), ylab = "Residuals")
Box.test(model$resid, lag = (1 + 1 + 4 + 1), type = "Ljung-Box", fitdf = (1 + 1 + 4))
```
Much better results.
```{r}
garch_spec <- ugarchspec(variance.model = list(model = "sGARCH", garchOrder = c(1, 1)), 
                         mean.model = list(armaOrder = c(0, 0), include.mean = TRUE),
                         distribution.model = "norm")
garch_fit <- ugarchfit(spec = garch_spec, data = residuals(res_model))
summary(garch_fit)
plot(sigma(garch_fit), type = "l", main = "Conditional Volatility (GARCH)")
forecast_horizon <- 4  
forecast_values <- predict(res_model, n.ahead = forecast_horizon)

forecasted_values <- forecast_values$pred

actual_values <- tail(saving_q, forecast_horizon)
forecasted_values_ts <- ts(forecasted_values, start = c(2024, 1), frequency = 4)


cat("Actual Values:\n")
print(actual_values)
cat("\nForecasted Values:\n")
print(forecasted_values_ts)

# Compute MAPE: Mean Absolute Percentage Error
mape <- mean(abs((actual_values - forecasted_values_ts) / actual_values)) * 100
cat("\nMAPE: ", mape, "%\n")

```
